import React from 'react';
import FaqCard from './FaqCard';

const faqData = [
  {
    question: "HOW OFTEN SHOULD I TAKE MY PET TO THE VET?",
    answer: "THE FREQUENCY OF VET VISITS DEPENDS ON YOUR PET'S AGE AND HEALTH. PUPPIES AND KITTENS NEED MULTIPLE CHECKUPS IN THEIR fiRST YEAR FOR VACCINATIONS AND ROUTINE EXAMS. FOR HEALTHY ADULT PETS, AN ANNUAL VISIT IS TYPICALLY SUFfiCIENT. OLDER PETS OR THOSE WITH HEALTH ISSUES MIGHT NEED CHECKUPS EVERY SIX MONTHS."
  },
  {
    question: "WHAT VACCINATIONS DOES MY PET NEED?",
    answer: "ESSENTIAL VACCINES FOR DOGS INCLUDE RABIES, DISTEMPER, AND PARVOVIRUS. FOR CATS, RABIES, FELINE LEUKEMIA, AND FVRCP (FELINE DISTEMPER) ARE COMMONLY RECOMMENDED YOUR VET CAN TAILOR A VACCINATION PLAN BASED ON YOUR PET'S LIFESTYLE AND ENVIRONMENT."
  },
  {
    question: "WHAT SHOULD I DO IF MY PET HAS flEAS OR TICKS?",
    answer: "START WITH A VET—RECOMMENDED flEA OR TICK TREATMENT. CLEAN YOUR PET'S BEDDING AND VACUUM YOUR HOME THOROUGHLY TO REMOVE PESTS. IN SEVERE CASES, YOU MAY NEED PROFESSIONAL PEST CONTROL. PREVENTATIVE TREATMENTS ARE KEY TO KEEPING fIEAS AND TICKS AWAY."
  },
  {
    question: "WHY DOES MY DOG BARK SO MUCH?",
    answer: "DOGS LAN BARK FOR VARIOUS REASONS DUE TO BOREDOM, ANXIETY, EXCITEMENT, OR TO ALERT YOU. U SHOULD DEFINITELY IDENTIFY THE TRIGGER fiRST. KEEP YOUR DOG MENTALLY AND PHYSICALLY STIMULATED WITH TOYS, WALKS, AND TRAINING IF ANXIETY CAUSES, U SHOULD CONSULT A VET OR PROFESSIONAL TRAINER."
  },
  {
    question: "HOW CAN I TELL IF MY CAT IS STRESSED?",
    answer: "MATS LAN EXPRESS STRESS IN SUBTLE WAYS SUCH AS HIDING, OVER—GROOMING, OR CHANGES IN APPETITE. CREATE A CALM, SAFE SPACE FOR THEM, MINIMIZE CHANGES IN THEIR ENVIRONMENT, AND CONSIDER USING CALMING SPRAYS OR PHEROMONES."
  },
  {
    question: "WHAT ARE THE SIGNS OF SEPARATION ANXIETY IN PETS?",
    answer: "PETS WITH SEPARATION ANXIETY MAY CHEW DESTRUCTIVELY, HOWL, OR PACE WHEN LEFT ALONE. GRADUAL TRAINING, CALMING COLLARS, OR INTERACTIVE TOYS CAN HELP. IF THE ISSUE PERSISTS A VET OR ANIMAL BEHAVIORIST CAN OFFER ADDITIONAL SOLUTIONS."
  },
  {
    question: "HOW CAN I TELL IF MY PET IS IN PAIN?",
    answer: "PETS ARE SKILLED AT HIDING DISCOMFORT, BUT SIGNS LIKE LIMPING, WHINING, REDUCED APPETITE, OR AVOIDING TOUCH MIGHT INDICATE PAIN. IF YOU NOTICE UNUSUAL BEHAVIOR, SCHEDULE A VET VISIT—BETTER TO BE CAUTIOUS."
  },
  {
    question: "WHAT SHOULD I FEED MY PET?",
    answer: "CHOOSE A BALANCED DIET APPROPRIATE FOR YOUR PET'S AGE, BREED, AND HEALTH. HIGH—QUALITY COMMERCIAL FOOD IS USUALLY A SAFE CHOICE. IF YOU PREFER HOMEMADE MEALS, CONSULT A VET OR PET NUTRITIONIST TO ENSURE THE DIET MEETS THEIR NUTRITIONAL NEEDS."
  },
  {
    question: "HOW MUCH EXERCISE DOES MY PET NEED?",
    answer: "EXERCISE REQUIREMENTS VARY. MOST DOGS THRIVE WITH 3O MINUTES TO 2 HOURS OF ACTIVITY DAILY, WHILE CATS ENJOY SHORT, PLAYFUL BURSTS. ADJUST BASED ON YOUR PET'S AGE, BREED, AND HEALTH, AND MONITOR FOR SIGNS OF FATIGUE OR OVEREXERTION."
  },
  {
    question: "HOW OFTEN SHOULD I BATHE MY PET?",
    answer: "DOGS GENERALLY NEED A BATH EVERY MONTH UNLESS THEY GET ESPECIALLY DIRTY. MATS USUALLY HANDLE GROOMING THEMSELVES BUT MAY NEED A BATH IF THEY GET INTO SOMETHING STICKY. ALWAYS USE PET—SPECIfiC SHAMPOOS."
  },
  {
    question: "HOW CAN I TAKE CARE OF MY PET'S TEETH?",
    answer: "BRUSH YOUR PET'S TEETH A FEW TIMES A WEEK WITH PET—SAFE TOOTHPASTE. DENTAL TREATS AND CHEW TOYS CAN HELP REDUGE PLAQUE. REGULAR DENTAL CHECKUPS WITH YOUR VET ARE ESSENTIAL TO CATCHING ANY ISSUES EARLY."
  },
  {
    question: "WHAT SHOULD I DO IF MY PET'S NAILS ARE TOO LONG?",
    answer: "IF YOU HEAR THEIR NAILS CLICKING ON THE fIOOR, IT'S TIME FOR A TRIM. USE PET NAIL CLIPPERS OR GRINDERS AND BE CAREFUL NOT TO CUT INTO THE QUICK. IF YOU'RE UNSURE, A VET OR GROOMER CAN HELP."
  },
  {
    question: "HOW DO I PET-PROOF MY HOME?",
    answer: "STORE CHEMICALS, SMALL OBJECTS, AND TOXIC PLANTS OUT OF REACH. HIDE ELECTRICAL CORDS AND SEGURE WINDOWS AND BALCONIES.USE COVERED TRASH CANS AND ENSURE YOUR HOME IS FREE OF HAZARDS THAT CURIOUS PETS MIGHT EXPLORE."
  },
  {
    question: "HOW CAN I KEEP MY PET SAFE DURING EXTREME WEATHER?",
    answer: "IN HOT WEATHER, KEEP YOUR PET HYDRATED AND LIMIT OUTDOOR ACTIVITIES DURING PEAK SUN HOURS. IN THE COLD, PROVIDE A WARM INDOOR SPACE AND CONSIDER PET—SAFE BOOTS OR JACKETS FOR SHORT—HAIRED BREEDS. MONITOR THEIR COMFORT CLOSELY."
  },
  {
    question: "HOW DO I KEEP MY PET ENTERTAINED WHEN I'M AwAy?",
    answer: "INTERACTIVE TOYS, PUZZLE FEEDERS, AND CHEW TOYS ARE GREAT FOR KEEPING PETS OCCUPIED. CALMING MUSIC OR A PET CAMERA WITH A MICROPHONE GAN HELP THEM FEEL LESS ALONE. A MORNING PLAY SESSION OR WALK CAN ALSO TIRE THEM OUT BEFORE YOU LEAVE."
  },
];

const FaqSection = () => {
  return (
    <div className="max-w-7xl mx-auto px-4 py-16 sm:px-6 lg:px-8">
      <div className="text-center mb-16">
        <h1 className="text-4xl font-bold text-green-700 mb-4 relative inline-block">
          Frequently Asked Questions
          <div className="absolute -bottom-2 left-0 right-0 h-1 bg-gradient-to-r from-emerald-400 to-emerald-300 rounded-full"></div>
        </h1>
        <p className="text-lg text-zinc-600 max-w-2xl mx-auto mt-6">
          Find answers to common questions about UIVerse and how to make the most of our platform.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {faqData.map((faq, index) => (
          <div key={index} className="transform hover:-translate-y-1 transition-transform duration-300">
            <FaqCard
              question={faq.question}
              answer={faq.answer}
            />
          </div>
        ))}
      </div>
    </div>
  );
};

export default FaqSection;
